In [3]:
sentences  = []
inputMediumfile = open("/content/CLIMATE_CHANGE1.txt")
for sentence in inputMediumfile:
  sentences.append(sentence)
print(sentences[10]) 

Different places can have different climates. 



In [88]:
import pandas as pd 
from sklearn.feature_extraction.text import TfidfVectorizer

vec = TfidfVectorizer()
tf_idf =  vec.fit_transform(sentences)

print(pd.DataFrame(tf_idf.toarray() ))


          0         1         2         3         4         5         6   \
0   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2   0.000000  0.000000  0.000000  0.156650  0.000000  0.000000  0.000000   
3   0.000000  0.176006  0.000000  0.132306  0.000000  0.000000  0.000000   
4   0.000000  0.000000  0.000000  0.231966  0.000000  0.000000  0.000000   
5   0.000000  0.000000  0.000000  0.000000  0.000000  0.354134  0.354134   
6   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
7   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8   0.000000  0.000000  0.000000  0.251229  0.000000  0.000000  0.000000   
9   0.000000  0.000000  0.000000  0.224360  0.000000  0.000000  0.000000   
10  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
11  0.368951  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
12  0.000000

In [ ]:
import gensim

# Load Google's pre-trained Word2Vec model.
model =  gensim.models.KeyedVectors.load_word2vec_format('/content/drive/MyDrive/GoogleNews-vectors-negative300.bin.gz', binary=True)  


In [75]:
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords

row = len(sentences)
col = len(vector2) 
sentenceMatrix = np.zeros((row, col),dtype=float)


i = 0
stopWords = set(stopwords.words('english'))
wordsFiltered = []

for i in range(row):
  words = word_tokenize(sentences[i])
  for w in words:
    if w not in stopWords:
      wordsFiltered.append(w)

  vector_total = np.zeros(col)
  for word_ in wordsFiltered:
    try:
      print(word_)
      vector1= model[word_]  
      vector_total = vector1 + vector_total
      #print(vector1)
    except KeyError:
      print("word '%s' not in vocabulary" % word_)
    sentenceMatrix[i,:] = vector_total


print("sentenceMatrix is  ", sentenceMatrix[3])

What
Is
Climate
?
word '?' not in vocabulary
How
Is
It
Different
From
Weather
?
word '?' not in vocabulary
What
Is
Climate
?
word '?' not in vocabulary
How
Is
It
Different
From
Weather
?
word '?' not in vocabulary
You
might
know
weather
.
word '.' not in vocabulary
Weather
changes
see
feel
outside
day
day
.
word '.' not in vocabulary
What
Is
Climate
?
word '?' not in vocabulary
How
Is
It
Different
From
Weather
?
word '?' not in vocabulary
You
might
know
weather
.
word '.' not in vocabulary
Weather
changes
see
feel
outside
day
day
.
word '.' not in vocabulary
It
might
rain
one
day
sunny
next
.
word '.' not in vocabulary
Sometimes
cold
.
word '.' not in vocabulary
Sometimes
hot
.
word '.' not in vocabulary
Weather
also
changes
place
place
.
word '.' not in vocabulary
What
Is
Climate
?
word '?' not in vocabulary
How
Is
It
Different
From
Weather
?
word '?' not in vocabulary
You
might
know
weather
.
word '.' not in vocabulary
Weather
changes
see
feel
outside
day
day
.
word '.' not in vocabu

In [79]:
dist_1 = spatial.distance.cosine(sentenceMatrix[1], sentenceMatrix[10])
print('dist_1 ',dist_1)

dist_1  0.26384973056686833


In [76]:

u,s,vh = np.linalg.svd(sentenceMatrix)


In [77]:
len(u)

23

In [78]:
u.shape , vh.shape, s.shape

((23, 23), (300, 300), (23,))

In [80]:
sen1 = u[:,:2]
vector1= sen1[1]
10 * vector1

array([0.24819887, 0.58816212])

In [81]:
sen2 = u[:,:2]
vector2 = sen2[10]
10 * vector2

array([1.70708145, 2.19030614])

In [82]:
u[1,:]

array([ 2.48198875e-02,  5.88162118e-02,  2.45052961e-01, -4.04843257e-01,
        3.32410284e-01, -1.64855265e-01,  2.01374929e-01, -3.73386195e-01,
       -3.33572764e-01,  1.82528414e-01, -2.48578278e-01, -2.18637043e-03,
        1.72648816e-02,  3.17513765e-01, -4.04791129e-02, -8.90845351e-03,
        2.07460975e-01, -1.90740513e-01, -6.23288047e-02,  1.03034414e-01,
       -1.83743459e-01,  1.32036644e-01,  1.00630863e-15])

In [83]:
u[10,:]

array([ 1.70708145e-01,  2.19030614e-01, -7.60019948e-02,  1.82261845e-01,
        4.51187973e-01, -1.01478936e-01,  2.06522727e-02,  2.70550962e-01,
       -8.34140810e-02, -2.42431961e-01, -2.68054663e-01,  6.09012745e-03,
        1.65110226e-01, -3.02439425e-02,  4.65646464e-03, -4.66087229e-01,
        2.96999623e-01,  1.17959538e-01,  1.19471400e-01, -1.73784384e-01,
        1.54460694e-01, -2.07082946e-01,  5.08452069e-16])

In [86]:

dist_1 = spatial.distance.cosine(u[1,:], u[10,:])
print('dist_1 ',dist_1)

dist_1  0.9999999999999999


In [ ]:

dist_1 = spatial.distance.cosine(u[1,:], u[10,:])
print('dist_1 ',dist_1)

In [87]:
dist_1 = spatial.distance.cosine(vector1[:2], vector2[:2])
print('dist_1 ',dist_1)

dist_1  0.034313374471512836


# Loading word2vec

In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [24]:
import numpy as np

row = len(sentences)
col = len(vector2) 
sentenceMatrix = np.zeros((row, col),dtype=int)

In [60]:
sentenceMatrix

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

finding the repreentation of sentences in form of word vectors 

## making sentence to concept mapping 

In [26]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')

from nltk.corpus import stopwords

stops = set(stopwords.words('english'))
print(stops)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


{'weren', 'mustn', "mightn't", 'he', 'have', 'ma', 'just', 'herself', 'being', 'a', "mustn't", 'each', 'themselves', "you've", 'again', 'off', 'should', 'she', 'between', 'o', 'while', 'ours', "shan't", 'but', 'of', 'here', 'd', "couldn't", 'your', 'all', "you'll", 'now', 'once', 'needn', "she's", 'few', 'they', "don't", 'me', 'on', 'i', 'hasn', 'was', 'did', 'or', 'any', 'against', 'having', 'not', "didn't", "isn't", 'by', 'won', 'very', 're', 'isn', 'been', 'up', 'the', 'its', 'mightn', 'an', "doesn't", 'be', "you're", 'couldn', 'who', 't', 'can', 'his', 'hers', 'were', 'myself', 'further', 'wouldn', 'shan', 'it', 'nor', 'to', "aren't", "hasn't", 'more', 'through', 'you', 'whom', 'about', 'into', 'in', 'm', 'am', 'after', 'during', 'are', 'our', 'when', 'own', 'shouldn', 'for', 'down', "needn't", "you'd", 'we', 'because', 'doesn', 'their', 'from', 'under', "wasn't", 'too', 'and', "it's", 'over', 'hadn', 'those', 'does', 'had', 'how', 'is', 'then', "hadn't", 'doing', 'with', 'him', "w

## Converting sentences to average of word representation

In [59]:
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords

row = len(sentences)
col = len(vector2) 
sentenceMatrix = np.zeros((row, col),dtype=float)


i = 1
stopWords = set(stopwords.words('english'))
wordsFiltered = []

words = word_tokenize(sentences[i])
for w in words:
  if w not in stopWords:
    wordsFiltered.append(w)

vector_total = np.zeros(col)
for word_ in wordsFiltered:
#  if (len(model[word_]) != 0): 
    try:
      print(word_)
      vector1= model[word_]  
      vector_total = vector1 + vector_total
      #print(vector1)
    except KeyError:
      print("word '%s' not in vocabulary" % word_)
    sentenceMatrix[i,:] = vector_total


print("sentenceMatrix is  ", sentenceMatrix[i])

What
Is
Climate
?
word '?' not in vocabulary
How
Is
It
Different
From
Weather
?
word '?' not in vocabulary
sentenceMatrix is   [ 0.20202637  0.92529297  0.43725586  1.00927734 -0.77832031  0.61608887
  0.54162598 -0.29724121  0.68811035  0.56704712  0.08325195 -1.22705078
 -0.97021484 -0.36035156 -0.72814941  1.15447998  0.05947876  1.75170898
  0.06884766 -1.34375    -0.91992188  1.75317383  2.57910156 -0.38232422
 -0.05210114  0.38043213 -1.72094727  0.3482666   1.09191895  0.95939779
 -0.41491699  0.03234863 -0.05517578 -0.03747559 -0.02731323  0.5612793
 -0.98278809  0.49084473 -0.77526855  1.52441406 -0.13378906 -0.55136108
 -0.47192383 -1.03753662 -0.03540039 -0.22668457 -1.12219238  0.2177124
  0.18017578  1.93457031 -2.96691895  1.83300781 -0.02893066 -1.56103516
  1.36724854  0.74725342 -0.50537109 -0.82983398  0.79916382 -0.21533203
 -0.31111145  0.77659607 -1.31445312 -0.78100586 -0.31445312 -0.36456299
  0.28900146  1.64147949 -0.43334961 -0.58862305  0.06176758 -0.08288574

## For all sentences, making the matrix to reduce

In [61]:
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords

row = len(sentences)
col = len(vector2) 
sentenceMatrix = np.zeros((row, col),dtype=float)


i = 0
stopWords = set(stopwords.words('english'))
wordsFiltered = []

for i in range(row):
  words = word_tokenize(sentences[i])
  for w in words:
    if w not in stopWords:
      wordsFiltered.append(w)

  vector_total = np.zeros(col)
  for word_ in wordsFiltered:
    try:
      print(word_)
      vector1= model[word_]  
      vector_total = vector1 + vector_total
      #print(vector1)
    except KeyError:
      print("word '%s' not in vocabulary" % word_)
    sentenceMatrix[i,:] = vector_total


print("sentenceMatrix is  ", sentenceMatrix[3])

What
Is
Climate
?
word '?' not in vocabulary
How
Is
It
Different
From
Weather
?
word '?' not in vocabulary
What
Is
Climate
?
word '?' not in vocabulary
How
Is
It
Different
From
Weather
?
word '?' not in vocabulary
You
might
know
weather
.
word '.' not in vocabulary
Weather
changes
see
feel
outside
day
day
.
word '.' not in vocabulary
What
Is
Climate
?
word '?' not in vocabulary
How
Is
It
Different
From
Weather
?
word '?' not in vocabulary
You
might
know
weather
.
word '.' not in vocabulary
Weather
changes
see
feel
outside
day
day
.
word '.' not in vocabulary
It
might
rain
one
day
sunny
next
.
word '.' not in vocabulary
Sometimes
cold
.
word '.' not in vocabulary
Sometimes
hot
.
word '.' not in vocabulary
Weather
also
changes
place
place
.
word '.' not in vocabulary
What
Is
Climate
?
word '?' not in vocabulary
How
Is
It
Different
From
Weather
?
word '?' not in vocabulary
You
might
know
weather
.
word '.' not in vocabulary
Weather
changes
see
feel
outside
day
day
.
word '.' not in vocabu